# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Jest

on:
    push:
        branches: [canary]
    pull_request:
        branches: [canary]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Run the tests and generate coverage report ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn
            - run: yarn test -- --coverage
            - name: Upload coverage to Codecov ${{ matrix.node-version }}
              uses: codecov/codecov-action@v1
